#pragma once

#define BLUEGRASS_META_STRINGIZE(text) BLUEGRASS_META_STRINGIZE_I(text)
#define BLUEGRASS_META_STRINGIZE_I(text) #text

#define BLUEGRASS_META_CAT(a, b)          BLUEGRASS_META_CAT_I(a, b)
#define BLUEGRASS_META_CAT_I(a, b)        a ## b

#define BLUEGRASS_META_EXPAND(x) BLUEGRASS_META_EXPAND_I(x)
#define BLUEGRASS_META_EXPAND_I(x) x

#define BLUEGRASS_META_GET_NTH_ARG(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, NAME, ...) NAME

#define BLUEGRASS_META_SEQ_SIZE(seq) BLUEGRASS_META_SEQ_SIZE_I(seq)
#define BLUEGRASS_META_SEQ_SIZE_I(seq) BLUEGRASS_META_CAT(BLUEGRASS_META_SEQ_SIZE_, BLUEGRASS_META_SEQ_SIZE_0 seq)

# define BLUEGRASS_META_SEQ_SIZE_0(_) BLUEGRASS_META_SEQ_SIZE_1
# define BLUEGRASS_META_SEQ_SIZE_1(_) BLUEGRASS_META_SEQ_SIZE_2
# define BLUEGRASS_META_SEQ_SIZE_2(_) BLUEGRASS_META_SEQ_SIZE_3
# define BLUEGRASS_META_SEQ_SIZE_3(_) BLUEGRASS_META_SEQ_SIZE_4
# define BLUEGRASS_META_SEQ_SIZE_4(_) BLUEGRASS_META_SEQ_SIZE_5
# define BLUEGRASS_META_SEQ_SIZE_5(_) BLUEGRASS_META_SEQ_SIZE_6
# define BLUEGRASS_META_SEQ_SIZE_6(_) BLUEGRASS_META_SEQ_SIZE_7
# define BLUEGRASS_META_SEQ_SIZE_7(_) BLUEGRASS_META_SEQ_SIZE_8
# define BLUEGRASS_META_SEQ_SIZE_8(_) BLUEGRASS_META_SEQ_SIZE_9
# define BLUEGRASS_META_SEQ_SIZE_9(_) BLUEGRASS_META_SEQ_SIZE_10
# define BLUEGRASS_META_SEQ_SIZE_10(_) BLUEGRASS_META_SEQ_SIZE_11
# define BLUEGRASS_META_SEQ_SIZE_11(_) BLUEGRASS_META_SEQ_SIZE_12
# define BLUEGRASS_META_SEQ_SIZE_12(_) BLUEGRASS_META_SEQ_SIZE_13
# define BLUEGRASS_META_SEQ_SIZE_13(_) BLUEGRASS_META_SEQ_SIZE_14
# define BLUEGRASS_META_SEQ_SIZE_14(_) BLUEGRASS_META_SEQ_SIZE_15
# define BLUEGRASS_META_SEQ_SIZE_15(_) BLUEGRASS_META_SEQ_SIZE_16
# define BLUEGRASS_META_SEQ_SIZE_16(_) BLUEGRASS_META_SEQ_SIZE_17
# define BLUEGRASS_META_SEQ_SIZE_17(_) BLUEGRASS_META_SEQ_SIZE_18
# define BLUEGRASS_META_SEQ_SIZE_18(_) BLUEGRASS_META_SEQ_SIZE_19
# define BLUEGRASS_META_SEQ_SIZE_19(_) BLUEGRASS_META_SEQ_SIZE_20
# define BLUEGRASS_META_SEQ_SIZE_20(_) BLUEGRASS_META_SEQ_SIZE_21
# define BLUEGRASS_META_SEQ_SIZE_21(_) BLUEGRASS_META_SEQ_SIZE_22
# define BLUEGRASS_META_SEQ_SIZE_22(_) BLUEGRASS_META_SEQ_SIZE_23
# define BLUEGRASS_META_SEQ_SIZE_23(_) BLUEGRASS_META_SEQ_SIZE_24
# define BLUEGRASS_META_SEQ_SIZE_24(_) BLUEGRASS_META_SEQ_SIZE_25
# define BLUEGRASS_META_SEQ_SIZE_25(_) BLUEGRASS_META_SEQ_SIZE_26
# define BLUEGRASS_META_SEQ_SIZE_26(_) BLUEGRASS_META_SEQ_SIZE_27
# define BLUEGRASS_META_SEQ_SIZE_27(_) BLUEGRASS_META_SEQ_SIZE_28
# define BLUEGRASS_META_SEQ_SIZE_28(_) BLUEGRASS_META_SEQ_SIZE_29
# define BLUEGRASS_META_SEQ_SIZE_29(_) BLUEGRASS_META_SEQ_SIZE_30
# define BLUEGRASS_META_SEQ_SIZE_30(_) BLUEGRASS_META_SEQ_SIZE_31
# define BLUEGRASS_META_SEQ_SIZE_31(_) BLUEGRASS_META_SEQ_SIZE_32
# define BLUEGRASS_META_SEQ_SIZE_32(_) BLUEGRASS_META_SEQ_SIZE_33

# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_0 0
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_1 1
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_2 2
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_3 3
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_4 4
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_5 5
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_6 6
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_7 7
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_8 8
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_9 9
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_10 10
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_11 11
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_12 12
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_13 13
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_14 14
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_15 15
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_16 16
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_17 17
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_18 18
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_19 19
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_20 20
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_21 21
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_22 22
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_23 23
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_24 24
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_25 25
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_26 26
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_27 27
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_28 28
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_29 29
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_30 30
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_31 31
# define BLUEGRASS_META_SEQ_SIZE_BLUEGRASS_META_SEQ_SIZE_32 32

#define BLUEGRASS_META_SEQ_ENUM(seq) BLUEGRASS_META_SEQ_ENUM_I(seq)
#define BLUEGRASS_META_SEQ_ENUM_I(seq) BLUEGRASS_META_CAT(BLUEGRASS_META_SEQ_ENUM_, BLUEGRASS_META_SEQ_SIZE(seq)) seq

# define BLUEGRASS_META_SEQ_ENUM_1(x) x
# define BLUEGRASS_META_SEQ_ENUM_2(x) x, BLUEGRASS_META_SEQ_ENUM_1
# define BLUEGRASS_META_SEQ_ENUM_3(x) x, BLUEGRASS_META_SEQ_ENUM_2
# define BLUEGRASS_META_SEQ_ENUM_4(x) x, BLUEGRASS_META_SEQ_ENUM_3
# define BLUEGRASS_META_SEQ_ENUM_5(x) x, BLUEGRASS_META_SEQ_ENUM_4
# define BLUEGRASS_META_SEQ_ENUM_6(x) x, BLUEGRASS_META_SEQ_ENUM_5
# define BLUEGRASS_META_SEQ_ENUM_7(x) x, BLUEGRASS_META_SEQ_ENUM_6
# define BLUEGRASS_META_SEQ_ENUM_8(x) x, BLUEGRASS_META_SEQ_ENUM_7
# define BLUEGRASS_META_SEQ_ENUM_9(x) x, BLUEGRASS_META_SEQ_ENUM_8
# define BLUEGRASS_META_SEQ_ENUM_10(x) x, BLUEGRASS_META_SEQ_ENUM_9
# define BLUEGRASS_META_SEQ_ENUM_11(x) x, BLUEGRASS_META_SEQ_ENUM_10
# define BLUEGRASS_META_SEQ_ENUM_12(x) x, BLUEGRASS_META_SEQ_ENUM_11
# define BLUEGRASS_META_SEQ_ENUM_13(x) x, BLUEGRASS_META_SEQ_ENUM_12
# define BLUEGRASS_META_SEQ_ENUM_14(x) x, BLUEGRASS_META_SEQ_ENUM_13
# define BLUEGRASS_META_SEQ_ENUM_15(x) x, BLUEGRASS_META_SEQ_ENUM_14
# define BLUEGRASS_META_SEQ_ENUM_16(x) x, BLUEGRASS_META_SEQ_ENUM_15
# define BLUEGRASS_META_SEQ_ENUM_17(x) x, BLUEGRASS_META_SEQ_ENUM_16
# define BLUEGRASS_META_SEQ_ENUM_18(x) x, BLUEGRASS_META_SEQ_ENUM_17
# define BLUEGRASS_META_SEQ_ENUM_19(x) x, BLUEGRASS_META_SEQ_ENUM_18
# define BLUEGRASS_META_SEQ_ENUM_20(x) x, BLUEGRASS_META_SEQ_ENUM_19
# define BLUEGRASS_META_SEQ_ENUM_21(x) x, BLUEGRASS_META_SEQ_ENUM_20
# define BLUEGRASS_META_SEQ_ENUM_22(x) x, BLUEGRASS_META_SEQ_ENUM_21
# define BLUEGRASS_META_SEQ_ENUM_23(x) x, BLUEGRASS_META_SEQ_ENUM_22
# define BLUEGRASS_META_SEQ_ENUM_24(x) x, BLUEGRASS_META_SEQ_ENUM_23
# define BLUEGRASS_META_SEQ_ENUM_25(x) x, BLUEGRASS_META_SEQ_ENUM_24
# define BLUEGRASS_META_SEQ_ENUM_26(x) x, BLUEGRASS_META_SEQ_ENUM_25
# define BLUEGRASS_META_SEQ_ENUM_27(x) x, BLUEGRASS_META_SEQ_ENUM_26
# define BLUEGRASS_META_SEQ_ENUM_28(x) x, BLUEGRASS_META_SEQ_ENUM_27
# define BLUEGRASS_META_SEQ_ENUM_29(x) x, BLUEGRASS_META_SEQ_ENUM_28
# define BLUEGRASS_META_SEQ_ENUM_30(x) x, BLUEGRASS_META_SEQ_ENUM_29
# define BLUEGRASS_META_SEQ_ENUM_31(x) x, BLUEGRASS_META_SEQ_ENUM_30
# define BLUEGRASS_META_SEQ_ENUM_32(x) x, BLUEGRASS_META_SEQ_ENUM_31

#define BLUEGRASS_META_FE0(MAC, ...)
#define BLUEGRASS_META_FE1(MAC,  A, B) MAC(A, B)
#define BLUEGRASS_META_FE2(MAC,  A, B, ...) MAC(A, B) BLUEGRASS_META_FE1(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE3(MAC,  A, B, ...) MAC(A, B) BLUEGRASS_META_FE2(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE4(MAC,  A, B, ...) MAC(A, B) BLUEGRASS_META_FE3(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE5(MAC,  A, B, ...) MAC(A, B) BLUEGRASS_META_FE4(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE6(MAC,  A, B, ...) MAC(A, B) BLUEGRASS_META_FE5(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE7(MAC,  A, B, ...) MAC(A, B) BLUEGRASS_META_FE6(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE8(MAC,  A, B, ...) MAC(A, B) BLUEGRASS_META_FE7(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE9(MAC,  A, B, ...) MAC(A, B) BLUEGRASS_META_FE8(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE10(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE9(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE11(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE10(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE12(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE11(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE13(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE12(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE14(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE13(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE15(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE14(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE16(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE15(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE17(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE16(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE18(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE17(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE19(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE18(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE20(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE19(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE21(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE20(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE22(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE21(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE23(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE22(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE24(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE23(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE25(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE24(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE26(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE25(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE27(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE26(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE28(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE27(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE29(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE28(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE30(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE29(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE31(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE30(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE32(MAC, A, B, ...) MAC(A, B) BLUEGRASS_META_FE31(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA2(MAC,  A, B, ...) MAC(A, B), BLUEGRASS_META_FE1(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA3(MAC,  A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA2(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA4(MAC,  A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA3(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA5(MAC,  A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA4(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA6(MAC,  A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA5(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA7(MAC,  A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA6(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA8(MAC,  A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA7(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA9(MAC,  A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA8(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA10(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA9(MAC,  A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA11(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA10(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA12(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA11(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA13(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA12(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA14(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA13(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA15(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA14(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA16(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA15(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA17(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA16(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA18(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA17(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA19(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA18(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA20(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA19(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA21(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA20(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA22(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA21(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA23(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA22(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA24(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA23(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA25(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA24(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA26(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA25(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA27(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA26(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA28(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA27(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA29(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA28(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA30(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA29(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA31(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA30(MAC, A, ##__VA_ARGS__)
#define BLUEGRASS_META_FE_COMMA32(MAC, A, B, ...) MAC(A, B), BLUEGRASS_META_FE_COMMA31(MAC, A, ##__VA_ARGS__)

#define BLUEGRASS_META_FOREACH_NO_COMMA(MAC, D, ...) \
   BLUEGRASS_META_GET_NTH_ARG("ignored", ##__VA_ARGS__, \
      BLUEGRASS_META_FE32,BLUEGRASS_META_FE31,BLUEGRASS_META_FE30,BLUEGRASS_META_FE29,BLUEGRASS_META_FE28,BLUEGRASS_META_FE27,BLUEGRASS_META_FE26,BLUEGRASS_META_FE25,BLUEGRASS_META_FE24,BLUEGRASS_META_FE23,BLUEGRASS_META_FE22,BLUEGRASS_META_FE21,BLUEGRASS_META_FE20,BLUEGRASS_META_FE19,BLUEGRASS_META_FE18,BLUEGRASS_META_FE17,BLUEGRASS_META_FE16,BLUEGRASS_META_FE15,BLUEGRASS_META_FE14,BLUEGRASS_META_FE13,BLUEGRASS_META_FE12,BLUEGRASS_META_FE11,BLUEGRASS_META_FE10,BLUEGRASS_META_FE9,BLUEGRASS_META_FE8,BLUEGRASS_META_FE7,BLUEGRASS_META_FE6,BLUEGRASS_META_FE5,BLUEGRASS_META_FE4,BLUEGRASS_META_FE3,BLUEGRASS_META_FE2,BLUEGRASS_META_FE1,BLUEGRASS_META_FE0)(MAC, D, ##__VA_ARGS__)

#define BLUEGRASS_META_FOREACH_SEQ_ARGS(MAC, D, SEQ) \
   (MAC, D, BLUEGRASS_META_SEQ_ENUM(SEQ))
#define BLUEGRASS_META_GET_NTH_ARG_SEQ_ARGS(...) \
   ("ignored", BLUEGRASS_META_SEQ_ENUM(__VA_ARGS__), BLUEGRASS_META_FE32,BLUEGRASS_META_FE31,BLUEGRASS_META_FE30,BLUEGRASS_META_FE29,BLUEGRASS_META_FE28,BLUEGRASS_META_FE27,BLUEGRASS_META_FE26,BLUEGRASS_META_FE25,BLUEGRASS_META_FE24,BLUEGRASS_META_FE23,BLUEGRASS_META_FE22,BLUEGRASS_META_FE21,BLUEGRASS_META_FE20,BLUEGRASS_META_FE19,BLUEGRASS_META_FE18,BLUEGRASS_META_FE17,BLUEGRASS_META_FE16,BLUEGRASS_META_FE15,BLUEGRASS_META_FE14,BLUEGRASS_META_FE13,BLUEGRASS_META_FE12,BLUEGRASS_META_FE11,BLUEGRASS_META_FE10,BLUEGRASS_META_FE9,BLUEGRASS_META_FE8,BLUEGRASS_META_FE7,BLUEGRASS_META_FE6,BLUEGRASS_META_FE5,BLUEGRASS_META_FE4,BLUEGRASS_META_FE3,BLUEGRASS_META_FE2,BLUEGRASS_META_FE1,BLUEGRASS_META_FE0)

#define BLUEGRASS_META_FOREACH_SEQ(MAC, D, ...) \
   BLUEGRASS_META_EXPAND(BLUEGRASS_META_EXPAND(BLUEGRASS_META_GET_NTH_ARG BLUEGRASS_META_GET_NTH_ARG_SEQ_ARGS(__VA_ARGS__)) BLUEGRASS_META_FOREACH_SEQ_ARGS(MAC, D, ##__VA_ARGS__))


#define BLUEGRASS_META_FOREACH(MAC, D, ...) \
   BLUEGRASS_META_GET_NTH_ARG("ignored", ##__VA_ARGS__, \
      BLUEGRASS_META_FE_COMMA32,BLUEGRASS_META_FE_COMMA31,BLUEGRASS_META_FE_COMMA30,BLUEGRASS_META_FE_COMMA29,BLUEGRASS_META_FE_COMMA28,BLUEGRASS_META_FE_COMMA27,BLUEGRASS_META_FE_COMMA26,BLUEGRASS_META_FE_COMMA25,BLUEGRASS_META_FE_COMMA24,BLUEGRASS_META_FE_COMMA23,BLUEGRASS_META_FE_COMMA22,BLUEGRASS_META_FE_COMMA21,BLUEGRASS_META_FE_COMMA20,BLUEGRASS_META_FE_COMMA19,BLUEGRASS_META_FE_COMMA18,BLUEGRASS_META_FE_COMMA17,BLUEGRASS_META_FE_COMMA16,BLUEGRASS_META_FE_COMMA15,BLUEGRASS_META_FE_COMMA14,BLUEGRASS_META_FE_COMMA13,BLUEGRASS_META_FE_COMMA12,BLUEGRASS_META_FE_COMMA11,BLUEGRASS_META_FE_COMMA10,BLUEGRASS_META_FE_COMMA9,BLUEGRASS_META_FE_COMMA8,BLUEGRASS_META_FE_COMMA7,BLUEGRASS_META_FE_COMMA6,BLUEGRASS_META_FE_COMMA5,BLUEGRASS_META_FE_COMMA4,BLUEGRASS_META_FE_COMMA3,BLUEGRASS_META_FE_COMMA2,BLUEGRASS_META_FE1,BLUEGRASS_META_FE0)(MAC, D, ##__VA_ARGS__)

#define BLUEGRASS_META_ARGS_NUM(...) \
   BLUEGRASS_META_GET_NTH_ARG(__VA_ARGS__, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1,)
#define BLUEGRASS_META_OVERLOAD(MAC, ...) \
   BLUEGRASS_META_CAT(MAC,BLUEGRASS_META_ARGS_NUM(__VA_ARGS__))